//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int id { get; set; }
        public Nullable<double> Attendance { get; set; }
        public string Note { get; set; }
        public Nullable<int> FK_Attendance { get; set; }
        public string FK_User { get; set; }
    
        public virtual Attendance Attendance1 { get; set; }
        public virtual User User { get; set; }
    }
}
