//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemdanh
    {
        public int dd_id { get; set; }
        public string sv_id { get; set; }
        public int ss_id { get; set; }
        public int mh_id { get; set; }
        public int stt_id { get; set; }
        public Nullable<int> tkb_id { get; set; }
    
        public virtual monhoc monhoc { get; set; }
        public virtual session session { get; set; }
        public virtual sinhvien sinhvien { get; set; }
        public virtual status status { get; set; }
    }
}
