//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichday
    {
        public int ld_id { get; set; }
        public int mh_id { get; set; }
        public string gv_id { get; set; }
        public int hk_id { get; set; }
        public int hk_nam { get; set; }
    
        public virtual giaovien giaovien { get; set; }
        public virtual hocki hocki { get; set; }
        public virtual monhoc monhoc { get; set; }
    }
}
