
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sep2018_MVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Report
{

    public int id { get; set; }

    public string Dear { get; set; }

    public Nullable<System.DateTime> createAt { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public Nullable<int> FK_People { get; set; }

    public Nullable<System.DateTime> BeginTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public string TypeReport { get; set; }



    public virtual Person Person { get; set; }

}

}
