
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sep2018_MVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Schedule
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Schedule()
    {

        this.ScheduleDetails = new HashSet<ScheduleDetail>();

    }


    public int id { get; set; }

    public string ScheduleName { get; set; }

    public Nullable<System.DateTime> DateBegin { get; set; }

    public Nullable<System.DateTime> DateEnd { get; set; }

    public Nullable<int> FK_Course { get; set; }

    public Nullable<int> FK_Semester { get; set; }



    public virtual Course Course { get; set; }

    public virtual Semester Semester { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }

}

}
