//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session()
        {
            this.diemdanhs = new HashSet<diemdanh>();
        }
    
        public int ss_id { get; set; }
        public int tkb_id { get; set; }
        public int us_id { get; set; }
        public Nullable<System.DateTime> ss_create { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diemdanh> diemdanhs { get; set; }
        public virtual thoikhoabieu thoikhoabieu { get; set; }
        public virtual usergiaovien usergiaovien { get; set; }
    }
}
