
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sep2018_MVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Subject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Subject()
    {

        this.Learnings = new HashSet<Learning>();

    }


    public int id { get; set; }

    public string SubjectName { get; set; }

    public Nullable<double> Lesson { get; set; }

    public string Unit_Lesson { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Learning> Learnings { get; set; }

}

}
