//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thoikhoabieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thoikhoabieu()
        {
            this.sessions = new HashSet<session>();
        }
    
        public int tkb_id { get; set; }
        public int mh_id { get; set; }
        public int lp_id { get; set; }
        public string gv_id { get; set; }
        public int pg_id { get; set; }
        public Nullable<System.DateTime> tkb_date { get; set; }
        public int hk_id { get; set; }
        public int hk_nam { get; set; }
    
        public virtual hocki hocki { get; set; }
        public virtual hocki hocki1 { get; set; }
        public virtual lop lop { get; set; }
        public virtual monhoc monhoc { get; set; }
        public virtual phong phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session> sessions { get; set; }
    }
}
