//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sep2018_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usergiaovu
    {
        public int usgvu_id { get; set; }
        public string usgvu_username { get; set; }
        public string usgvu_pw { get; set; }
        public int role_id { get; set; }
    
        public virtual giaovu giaovu { get; set; }
        public virtual role role { get; set; }
    }
}
